spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <github:clientid>
            client-secret: <github:secretkey>
  data:
    cassandra:
      keyspace-name: main
      username: <astra:username>
      password: <astra:password>
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  logging.level.org.springframework.data.cassandra.core.cql.CqlTemplate: DEBUG

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: <astra:id>
  region: asia-south1
  keyspace: main
  application.token: <AstraCS:Token>